name: Puppeteer Workflow for Villages

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
    
    - name: Run Puppeteer script
      run: node test.js
      
    - name: Commit and push updated CSV (if applicable)
      run: |
        git config --local user.email "diassavio629@gmail.com"
        git config --local user.name "Savio629"
        git add data-villages
        git commit -m "Update data-villages folder"
        git pull --no-rebase
        git push https://${{ secrets.GH_TOKEN }}@github.com/Savio629/workflow-testing.git
      if: success()
